#!/usr/bin/env bash

BG="background-color: transparent"
STYLE="style=\"font-size: 9pt; font-family: angkor; color: rgba(244,244,244,100%); background-color: transparent;\""
STYLE2="style=\"font-size: 9pt; font-family: angkor; color: rgba(244,244,244,100%); background-color: transparent;\""
LINE="repo."
LINEA="AUR."
SEP=" "

myOutputTable="<table border=\"0\"><tr><td $STYLE>$LINE</td><td $STYLE2>$UPR</td><td>$SEP</td><td>$SEP</td><td $STYLE>$LINEA</td><td $STYLE2>$AUR</td></tr></table>"

echo "$myOutputTable"
